"use client";

import Head from "next/head";
import Home from "@/src/Views/Home/Home";

export default function Index() {
	return (
		<>
			<Head>
				<title>My Space</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Home />
		</>
	);
}
