"use client";

import Head from "next/head";
import NavMenu from "@/src/components/NavMenu/NavMenu";

export default function Home() {
	return (
		<>
			<Head>
				<title>My Space</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavMenu />
		</>
	);
}
